steps:
# Step 1: Build the pos-poller image
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t',
    'us-central1-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO_NAME}/pos-poller:${SHORT_SHA}',
    './pos-poller'
  ]

# Step 2: Build the pos-processor image
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t',
    'us-central1-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO_NAME}/pos-processor:${SHORT_SHA}',
    './pos-processor'
  ]

# After the steps are complete, list the images that were built.
images:
- 'us-central1-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO_NAME}/pos-poller:${SHORT_SHA}'
- 'us-central1-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO_NAME}/pos-processor:${SHORT_SHA}'

# THIS IS THE FIX: Tell Cloud Build where to send logs
options:
  logging: CLOUD_LOGGING_ONLY