# cloudbuild.yaml

steps:
  # Step 1: Build the specified container image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-service'
    args:
      - 'build'
      - '-t'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO_NAME}/${_SERVICE_NAME}:${_TAG}'
      - '-f'
      - '${_SERVICE_DIR}/Dockerfile'
      - '.'

# Push the built image to Artifact Registry
images:
  - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO_NAME}/${_SERVICE_NAME}:${_TAG}'

# Define build options, including the logging configuration
options:
  logging: CLOUD_LOGGING_ONLY