# .github/workflows/deploy-poller.yml
name: Build and Deploy POS Poller

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'pos-poller/**'
      - '.github/workflows/deploy-poller.yml'
      - '.github/workflows/reusable-deploy.yml' # Also trigger if the reusable workflow changes

jobs:
  call-reusable-deploy:
    name: Deploy POS Poller
    uses: ./.github/workflows/reusable-deploy.yml
    permissions:
      contents: read # Required for the checkout action
      id-token: write # Required for authenticating to Google Cloud
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    with:
      service_name: "pos-poller"
      service_specific_env_vars: "TOPIC_ID=pos-events,API_BASE_URL=https://ecm-nsoeservices-bethpage.cbsnorthstar.com/reportservice/salesdata.svc,SITE_ID_SECRET_ID=pos-site-id,API_ACCESS_TOKEN_SECRET_ID=pos-api-access-token"
    secrets: inherit