# .github/workflows/deploy.yml
name: Build and Deploy to Cloud Run

# This workflow is triggered on every push to the 'main' branch.
on:
  push:
    branches: [ "main" ]

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: "us-central1"
  REPO_NAME: "pos-services"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Required for Workload Identity Federation

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      id: auth
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

    - name: Set up Google Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Submit build to Cloud Build
      run: |
        gcloud builds submit . \
          --config=cloudbuild.yaml \
          --substitutions=_REGION=${{ env.GCP_REGION }},_REPO_NAME=${{ env.REPO_NAME }}