# .github/workflows/deploy-processor.yml
name: Build and Deploy POS Processor

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  push:
    branches: [ "main" ]
    # Only trigger if there are changes in the processor's source code or this workflow file.
    paths:
      - 'pos-processor/**'
      - '.github/workflows/deploy-processor.yml'

env:
  # These are defined as secrets in the GitHub repository settings.
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_WIF_PROVIDER: ${{ secrets.GCP_WIF_PROVIDER }}
  GCP_DEPLOYER_SA_EMAIL: ${{ secrets.GCP_DEPLOYER_SA_EMAIL }}
  # These are non-secret environment variables.
  GCP_REGION: "us-central1"
  ARTIFACT_REPO: "pos-services"
  SERVICE_NAME: "pos-processor"
  # The service account that Cloud Build will use to build and push to Artifact Registry.
  GCP_CLOUDBUILD_SA: "projects/${{ secrets.GCP_PROJECT_ID }}/serviceAccounts/manual-cloud-build-sa@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com"

jobs:
  build-and-deploy:
    # Add a concurrency group to cancel older runs of this workflow
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    name: Build and Deploy Processor
    runs-on: ubuntu-latest

    # These permissions are required for Workload Identity Federation.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.GCP_WIF_PROVIDER }}
          service_account: ${{ env.GCP_DEPLOYER_SA_EMAIL }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Cloud Build logging
        run: gcloud config set builds/logging CLOUD_LOGGING_ONLY

      - name: Build and Push container image
        run: |-
          gcloud builds submit pos-processor \
            --tag "${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.SERVICE_NAME }}:latest" \
            --service-account="${{ env.GCP_CLOUDBUILD_SA }}"

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image "${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.SERVICE_NAME }}:latest" \
            --region ${{ env.GCP_REGION }} \
            --quiet