# .github/workflows/deploy-processor.yml
name: Build and Deploy POS Processor

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'pos_processor/**'
      # Redeploy the processor if any data schema changes, as it's responsible for BigQuery insertion.
      - 'schemas/**.json'
      - '.github/workflows/deploy-processor.yml'
      - '.github/workflows/reusable-deploy.yml' # Also trigger if the reusable workflow changes

jobs:
  call-reusable-deploy:
    name: Deploy POS Processor
    uses: ./.github/workflows/reusable-deploy.yml
    permissions:
      contents: read # Required for the checkout action
      id-token: write # Required for authenticating to Google Cloud
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    with:
      service_name: "pos-processor"
      service_dir: "pos_processor"
      service_specific_env_vars: "BIGQUERY_DATASET_ID=pos_data"
    secrets: inherit