# .github/workflows/reusable-deploy.yml
name: Reusable Cloud Run Deployment

on:
  workflow_call:
    inputs:
      service_name:
        description: 'The name of the Cloud Run service.'
        required: true
        type: string
      service_dir:
        description: 'The directory containing the service source code.'
        required: true
        type: string
      service_specific_env_vars:
        description: 'Comma-separated list of KEY=VALUE environment variables for the service.'
        required: false
        type: string
    # FIX: Explicitly define the secrets the reusable workflow needs.
    # This allows the `secrets: inherit` in the calling workflow to pass them through.
    secrets:
      GCP_WIF_PROVIDER:
        required: true
      GCP_DEPLOYER_SA_EMAIL:
        required: true
      GCP_PROJECT_ID:
        required: true

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: "us-central1"

jobs:
  build-and-deploy:
    name: Build and Deploy ${{ inputs.service_name }}
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Required for Workload Identity Federation

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      id: auth
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
        service_account: ${{ secrets.GCP_DEPLOYER_SA_EMAIL }}
        # Best practice: create a credentials file for gcloud to use.
        create_credentials_file: true

    - name: Build and Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ inputs.service_name }} \
          --source ./${{ inputs.service_dir }} \
          --region ${{ env.GCP_REGION }} \
          --project ${{ env.GCP_PROJECT_ID }} \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars "${{ inputs.service_specific_env_vars }}"