# .github/workflows/test.yml
name: Run Tests

# This workflow is triggered on every pull request that targets the 'main' branch.
on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies and Run Tests
      run: |
        python -m pip install --upgrade pip
        pip install -r pos-poller/requirements.txt -r pos-processor/requirements.txt pytest
        pytest