# .github/workflows/test.yml

name: Run Tests

# Trigger this workflow on every pull request to the main branch
on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Install Dependencies and Run Pytest
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository code
      - name: Check out code
        uses: actions/checkout@v4

      # 2. Set up the Python environment
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # 3. Install dependencies for both services
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r pos-poller/requirements.txt
          pip install -r pos-processor/requirements.txt
          pip install pytest  # Install the testing framework

      # 4. Run tests with pytest
      - name: Run pytest
        run: pytest
